### ISSUE TITLE
Can you create a discussion board?

### ISSUE THREAD

**Issue by Sciumo** [NeuralVox/OpenPhonemizer#2]
Discussion or Q&A boards are a great way to have easy user engagement.

https://docs.github.com/en/discussions/quickstart

e.g. I would ask about emotive markup.
Something like Markdown but for TTS with emotives.

https://murf.ai/resources/text-to-speech-with-emotions/

**Comment by Sciumo** [comment]
then train classifiers on emotive markdown for making LLM training data sets for book translation in OP markdown format.

**Comment by fakerybakery** [comment]
Hi, I just enabled Discussions!
For emotional TTS, has you looked into SSML?

**Comment by Sciumo** [comment]
and there it is.
https://github.com/NeuralVox/OpenPhonemizer/discussions
