### ISSUE TITLE
Incorrect disambiguation of homonyms

### ISSUE THREAD

**Issue by geneing** [NeuralVox/OpenPhonemizer#5]
On a test phrase

> He wound it around the wound, saying "I read it was $10 to read."

OpenPhonemizer (both versions) produce: 

> hiː wˈuːnd ɪt ɚɹˈaʊnd ðə wˈuːnd, sˈeɪɪŋ ˈaɪ ɹˈiːd ɪt wʌz tˈɛn tuː ɹˈiːd . 

Gruut correctly phonemizes both uses of wound and read:

> hˈi wˈaʊnd ˈɪt ɚˈaʊnd ðə wˈund | sˈeɪɪŋ ˈaɪ ɹˈɛd ˈɪt wəz tˈɛn dˈɑlɚz tə ɹˈid ‖

**Comment by fakerybakery** [comment]
See #6
