### ISSUE TITLE
Incorrect handling of some proper names

### ISSUE THREAD

**Issue by geneing** [NeuralVox/OpenPhonemizer#6]
For a test phrase:

> I visited Bologna and ate a bologna sandwich.

Phonemizer correctly handles Bologna vs bologna:

> aɪ vˈɪzɪɾᵻd bəlˈoʊnʲə ænd ˈeɪt ɐ bəlˈoʊni sˈændwɪtʃ .

OpenPhonemizer: 

> ˈaɪ vˈɪzɪɾᵻd bəlˈoʊni ænd ˈeɪt ɐ bəlˈoʊni sˈændwɪtʃ .

**Comment by fakerybakery** [comment]
Hi, unfortunately as DeepPhonemizer doesn’t use a rule-based system but instead trains a model on many words, it’s difficult to fix this issue besides adding that word to the training dataset. I’m planning to train a multilingual model soon and I’ll add that word.
